# KNN Model & Model Comparison
This notebook explores KNN as a distance-based learning approach and compares it with previous models.


In [4]:
import numpy as np
import pandas as pd 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix


In [5]:

data_path="C:/Users/prasad/OneDrive/Documents/student-performance-risk-prediction/data/raw/student-mat.csv"
df=pd.read_csv(data_path,sep=';')

# Create target variable
def assign_risk(grade):
    if grade < 10:
        return "High"
    elif grade < 15:
        return "Medium"
    else:
        return "Low"

df["risk_level"] = df["G3"].apply(assign_risk)

# Remove leakage features
df = df.drop(columns=["G1", "G2", "G3"])


In [6]:
X = df.drop(columns=["risk_level"])
y=df["risk_level"]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


In [11]:
numeric_features = X.select_dtypes(exclude="object").columns
categorical_features = X.select_dtypes(include=["object"]).columns

numeric_features, categorical_features


(Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
        'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences'],
       dtype='object'),
 Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
        'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
        'nursery', 'higher', 'internet', 'romantic'],
       dtype='object'))

## Why Scaling is Mandatory for KNN

KNN uses distance calculations.
If features are on different scales, features with larger ranges dominate distance calculations.

Therefore:
- Numeric features are scaled
- Categorical features are encoded


In [14]:
knn_preprocessor=ColumnTransformer(
    transformers=[
        ("cat",OneHotEncoder(drop="first",handle_unknown="ignore"),categorical_features),
        ("num",StandardScaler(),numeric_features)
    ])

## KNN Model Intuition

KNN classifies a student based on the majority class among its nearest neighbors.
The value of K controls the balance between noise sensitivity and generalization.


In [19]:
knn_model=Pipeline(steps=[
    ("preprocessing",knn_preprocessor),
    ("classifier",KNeighborsClassifier(n_neighbors=7))
     ])

In [20]:
knn_model.fit(X_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')),
                                                 ('num', StandardScaler(),
                                                  Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel',
       'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences'],
      dtype='object'))])),
                ('classifier', KNeighborsClassifier(n_neighbors=7))])

In [22]:
y_pred_knn=knn_model.predict(X_test)
print(classification_report(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))

              precision    recall  f1-score   support

        High       0.29      0.19      0.23        26
         Low       0.25      0.13      0.17        15
      Medium       0.48      0.68      0.57        38

    accuracy                           0.42        79
   macro avg       0.34      0.34      0.32        79
weighted avg       0.38      0.42      0.38        79

[[ 5  2 19]
 [ 4  2  9]
 [ 8  4 26]]


## KNN Results Interpretation

The KNN model struggles to achieve strong performance, particularly for minority risk classes.
This is expected due to:
- Class imbalance
- High-dimensional encoded data
- Sensitivity to noisy neighbors

These results highlight the limitations of KNN for this dataset.


## Model Comparison

All evaluated models are compared based on performance, stability, and interpretability.
we select Controlled Decision Tree 
